import React from "react";
import { Row, Col, Label } from "reactstrap";
import LocationIcon from "../assets/images/location.png";
import CallIcon from "../assets/images/call.png";
import MessageIcon from "../assets/images/message.png";
import facebook from "../assets/images/facebook.png";
import twitter from "../assets/images/twitter.png";
import instagram from "../assets/images/instagram.png";

class AboutUs extends React.Component {
  render() {
    return (
      <div id="AboutUs">
        <div className="about-container">
          <div className="about_row">
            <h1>Weownomy Chat</h1>
            <h4>
              WeownomyChat is a social messaging app that <br />
              rewards users with cryptocurrency for using the app.
            </h4>
          </div>
          <div className="about_detail">
            <Label>About</Label>
            <Row>
              <Col md={4}>
                <p>
                  Weownomy Platform Corporation, Incorporated in the State of
                  Delaware https://www.weownomy.global is launching a
                  subscription based, open and participatory platform. A new
                  redefined social network that facilitates people's
                  participation in the democratic process of defining their own
                  rules for their future, generating an ownership structure
                  where every person has rights to share in the proceeds
                  generated by this new economy and hence true economic equality
                </p>
              </Col>
              <Col md={4} className="pading-left2">
                <span>F.A.Q</span>
                <span>Privacy policy</span>
                <span>Terms & Condition</span>
              </Col>
              <Col md={4}>
                <div className="about_address">
                  <div className="circle-ripple"></div>
                  <div className="about_box arrow-top">
                    <Row>
                      <Col md={2}>
                        <img src={LocationIcon} alt="LocationIcon" />
                      </Col>
                      <Col md={10}>
                        <Label className="address">
                          256 Chapman Road <br />
                          STE 105-4,
                          <br />
                          Delaware United
                          <br />
                          State of America
                        </Label>
                      </Col>
                    </Row>
                    <Row>
                      <Col md={2}>
                        <img src={CallIcon} alt="CallIcon" />
                      </Col>
                      <Col md={10}>
                        <Label className="mobileNo">
                          302-565-3849 <br />
                          +26656553721
                        </Label>
                      </Col>
                    </Row>
                    <Row>
                      <Col md={2}>
                        <img src={MessageIcon} alt="MessageIcon" />
                      </Col>
                      <Col md={10}>
                        <Label className="mobileNo">
                          office@weownomy.global
                        </Label>
                      </Col>
                    </Row>
                    <Row>
                      <div className="social_icons">
                        <img
                          src={facebook}
                          alt="Facebook"
                          className="fb-icon"
                        />
                        <img src={twitter} alt="Twitter" />
                        <img src={instagram} alt="Instagram" />
                      </div>
                    </Row>
                  </div>
                </div>
              </Col>
            </Row>
          </div>
        </div>
        <div className="border_line"></div>
        <div className="copy_text">
          <Label>@ Copyright 2021 Company. All rights reserved.</Label>
        </div>
      </div>
    );
  }
}

export default AboutUs;
